version: '2.2'

services:
  app:
    image: todo-list:spring-docker
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todolist?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: shubham
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db

  db:
    image: mysql:8.0.34
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: todolist
      MYSQL_USER: shubham
      MYSQL_PASSWORD: admin